"""Stage 6 (part 2) — the induced taxonomy.

Turns the multi-level clustering and labeling into the paper's taxonomy: a
table of axes (level x dimension) whose categories are the controlled-vocabulary
labels (structural dimensions) and cluster names (model type / text-derived
domain and approach). Emits a JSON structure, a flat CSV, and a LaTeX table in
the shape of the paper's ``tab:taxonomy_axes``.
"""

from __future__ import annotations

import csv
import io
from typing import Any

from lp2graph.mining.cluster import LevelResult, Taxonomy

from . import _lp2graph  # noqa: F401
from .labeling import LabelingResult


def _cluster_categories(level: LevelResult) -> list[str]:
    """Distinct, sorted cluster names for a level (drops the unassigned bucket)."""
    names = level.clustering.names
    cats = {n for n in names.values() if n and n != "unassigned"}
    return sorted(cats)


def _label_categories(labeling: LabelingResult, dimension: str) -> list[str]:
    dim = labeling.dimensions.get(dimension)
    if dim is None:
        return []
    return sorted({o.value for o in dim.outcomes if o.value != "unassigned"})


def build_taxonomy_axes(tax: Taxonomy, labeling: LabelingResult) -> list[dict[str, Any]]:
    """The five taxonomy axes with their induced categories."""
    return [
        {
            "level": "Variable/parameter",
            "dimension": "type",
            "derived_from": "structure + lexical",
            "categories": _label_categories(labeling, "variable_type")
            or _cluster_categories(tax.level_v),
        },
        {
            "level": "Constraint",
            "dimension": "family",
            "derived_from": "structure + lexical",
            "categories": _label_categories(labeling, "constraint_family")
            or _cluster_categories(tax.level_c),
        },
        {
            "level": "Model",
            "dimension": "type",
            "derived_from": "structure",
            "categories": _cluster_categories(tax.level_m),
        },
        {
            "level": "Model",
            "dimension": "domain",
            "derived_from": "text",
            "categories": _cluster_categories(tax.domain),
        },
        {
            "level": "Model",
            "dimension": "solution approach",
            "derived_from": "text",
            "categories": _cluster_categories(tax.solution_approach),
        },
    ]


def build_taxonomy(tax: Taxonomy, labeling: LabelingResult) -> dict[str, Any]:
    """The full taxonomy artifact: cluster counts, names, and the axes table."""
    return {
        "cluster_counts": tax.summary(),
        "axes": build_taxonomy_axes(tax, labeling),
    }


def to_csv(axes: list[dict[str, Any]]) -> str:
    """Flat CSV: one row per (level, dimension) with categories joined by ``;``."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["level", "dimension", "derived_from", "categories"])
    for ax in axes:
        writer.writerow(
            [ax["level"], ax["dimension"], ax["derived_from"], "; ".join(ax["categories"])]
        )
    return buf.getvalue()


def _tex_escape(s: str) -> str:
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def to_latex(axes: list[dict[str, Any]]) -> str:
    """A ``tabularx`` table matching the paper's ``tab:taxonomy_axes`` shape."""
    lines = [
        r"\begin{table}[h]",
        r"\centering",
        r"\caption{Axes of the induced taxonomy (generated by raiLPminer).}",
        r"\label{tab:taxonomy_axes}",
        r"\small",
        r"\begin{tabularx}{\linewidth}{@{}l l l X@{}}",
        r"\toprule",
        r"\textbf{Level} & \textbf{Dimension} & \textbf{Derived from} & \textbf{Categories} \\",
        r"\midrule",
    ]
    for ax in axes:
        cats = ", ".join(_tex_escape(c) for c in ax["categories"]) or "--"
        lines.append(
            f"{_tex_escape(ax['level'])} & {_tex_escape(ax['dimension'])} & "
            f"{_tex_escape(ax['derived_from'])} & {cats} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabularx}", r"\end{table}", ""]
    return "\n".join(lines)


__all__ = ["build_taxonomy", "build_taxonomy_axes", "to_csv", "to_latex"]
